name: Build, Test and Publish

permissions: read-all

on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]


jobs:
  build_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "0.4.17"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Run Tox
        run: |
          uv tool install tox --with tox-uv
          uv sync --all-extras --dev
          tox -p
